"""Per-session journal (JSONL) and deterministic gdbscript compilation.

Every server->plugin request and plugin->server notification is appended
to ``<log_dir>/journals/<session_id>.jsonl`` (long values trimmed, never
silently dropped). The journal is the audit trail AND the source for
``export_session_script``: state-mutating operations compile back into a
deterministic gdbscript that replays the session without gdb-mcp —
which is exactly the "LLM could have just written a gdbscript" challenge
turned into an acceptance test.
"""

from __future__ import annotations

import json
import re
import time
from pathlib import Path

#: single string fields longer than this are trimmed with a length note
MAX_FIELD = 256
#: hex payloads kept verbatim below this (beyond it a length marker is
#: recorded and script compilation degrades to a comment for that op)
MAX_HEX = 8192
#: list fields keep at most this many elements
MAX_LIST = 32
#: writes larger than this are not compiled into the script
MAX_COMPILE_WRITE = 256


def _trim(value, depth: int = 0):
    if isinstance(value, str):
        if len(value) > MAX_HEX:
            body = value[2:] if value[:2] in ("0x", "0X") else value
            if body and all(c in "0123456789abcdefABCDEF" for c in body):
                return "<hex:%d bytes>" % (len(body) // 2)
        if len(value) > MAX_FIELD:
            return value[:MAX_FIELD] + "...<+%d chars>" % (len(value) - MAX_FIELD)
        return value
    if isinstance(value, dict):
        if depth > 4:
            return "<...>"
        return {str(k): _trim(v, depth + 1) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        trimmed = [_trim(v, depth + 1) for v in list(value)[:MAX_LIST]]
        if len(value) > MAX_LIST:
            trimmed.append("<+%d more>" % (len(value) - MAX_LIST))
        return trimmed
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


class Journal:
    """Append-only JSONL writer with an in-memory mirror for exports."""

    def __init__(self, path: Path):
        self.path = Path(path)
        self._entries: list[dict] = []
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
        except OSError:
            pass

    def append(self, kind: str, data: dict) -> None:
        entry = {"ts": round(time.time(), 3), "kind": kind, **_trim(data)}
        self._entries.append(entry)
        try:
            with open(self.path, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(entry, ensure_ascii=False) + "\n")
        except OSError:
            pass  # journaling must never break debugging

    def entries(self) -> list[dict]:
        return list(self._entries)

    def __len__(self) -> int:
        return len(self._entries)


# --- gdbscript compilation --------------------------------------------------

#: verbs that only read state — they leave no trace in a replay script
_READ_VERBS = frozenset(
    {
        "read_mem",
        "regs",
        "backtrace",
        "disasm",
        "evaluate",
        "threads",
        "frame_select",
        "breakpoints",
        "mem_map",
        "snapshot_list",
        "snapshot_diff",
        "ping",
    }
)

_CONTINUE_CMDS = {
    "continue": "continue",
    "step": "step",
    "next": "next",
    "stepi": "stepi",
    "nexti": "nexti",
    "finish": "finish",
}


def compile_gdbscript(meta: dict, entries: list[dict]) -> tuple[str, dict]:
    """Compile journal entries into a deterministic gdbscript.

    Only state-mutating / control-flow operations are emitted; pure reads
    and plugin-specific checkpoint verbs are skipped with counters (the
    snapshot verbs cannot replay without the gdb-mcp plugin, and pretending
    otherwise would produce a lying script).
    """
    lines = [
        "# generated by gdb-mcp export_session_script",
        "# session: %s" % meta.get("session_id"),
    ]
    if meta.get("inferior"):
        lines.append("# inferior: %s" % meta["inferior"])
    used = 0
    reads = 0
    skipped = 0
    for entry in entries:
        if entry.get("kind") == "notification":
            continue
        if entry.get("kind") != "request":
            continue
        verb = entry.get("verb")
        params = entry.get("params") or {}
        if not entry.get("ok", True):
            skipped += 1  # failed operations do not replay
            continue
        if verb in _READ_VERBS or verb == "ping":
            reads += 1
            continue
        emitted: list[str] | None
        if verb == "eval":
            emitted = [str(params.get("command", ""))]
        elif verb == "file":
            emitted = ["file %s" % params.get("path")]
        elif verb == "core":
            emitted = ["core-file %s" % params.get("path")]
        elif verb == "break":
            emitted = _compile_break(params)
        elif verb == "bp_delete":
            emitted = ["delete %s" % params.get("number")]
        elif verb == "bp_enable":
            emitted = ["enable %s" % params.get("number")]
        elif verb == "bp_disable":
            emitted = ["disable %s" % params.get("number")]
        elif verb == "set_reg":
            emitted = ["set $%s = %s" % (params.get("name"), params.get("value"))]
        elif verb == "write_mem":
            emitted = _compile_write_mem(params)
        elif verb in _CONTINUE_CMDS:
            emitted = [_CONTINUE_CMDS[verb]]
        elif verb == "until":
            addr = params.get("until_addr")
            emitted = ["until *%s" % addr] if addr else ["until"]
        elif verb in ("snapshot_create", "snapshot_restore"):
            emitted = [
                "# checkpoint %s (plugin-specific; not replayable here)"
                % verb.split("_")[1]
            ]
            used += 1
            lines.extend(emitted)
            continue
        else:
            emitted = None
        if emitted is None:
            skipped += 1
            continue
        used += 1
        lines.extend(emitted)
    lines.append("quit")
    stats = {"used": used, "reads": reads, "skipped": skipped}
    return "\n".join(lines) + "\n", stats


def _compile_break(params: dict) -> list[str]:
    location = params.get("location", "")
    cmd = "tbreak" if params.get("temporary") else "break"
    lines = []
    if params.get("pending"):
        lines.append("set breakpoint pending on")
    condition = params.get("condition")
    lines.append(
        "%s %s if %s" % (cmd, location, condition)
        if condition
        else "%s %s" % (cmd, location)
    )
    commands = params.get("commands") or []
    if params.get("auto_continue") or commands:
        lines.append("commands")
        lines.append("silent")
        lines.extend(str(c) for c in commands)
        if params.get("auto_continue"):
            lines.append("continue")
        lines.append("end")
    if params.get("pending"):
        lines.append("set breakpoint pending auto")
    return lines


_HEX_ADDR_RE = re.compile(r"0x[0-9a-fA-F]+")


def _compile_write_mem(params: dict) -> list[str] | None:
    """Per-byte ``set {unsigned char}`` writes; only numeric addresses and
    bounded payloads compile — everything else degrades to None (skipped
    with a counter) rather than emitting a script that lies."""
    try:
        data = bytes.fromhex(str(params.get("hex", "")))
    except ValueError:
        return None
    if not data or len(data) > MAX_COMPILE_WRITE:
        return None
    addr = params.get("addr")
    if isinstance(addr, bool):
        return None
    if isinstance(addr, int):
        base = addr
    elif isinstance(addr, str) and re.fullmatch(r"0x[0-9a-fA-F]+", addr.strip()):
        base = int(addr.strip(), 16)
    else:
        return None
    return [
        "set {unsigned char}0x%x = 0x%02x" % (base + off, byte)
        for off, byte in enumerate(data)
    ]
